=head1 Output

 Info send to client:
 * job_id
 * rcommit_id - for first jobp

=head1 Relevant tables

 wconf_job
 * wconf_session_id ---> wconf_session.machine_id
 * rref_id ... ---> 1x rcommit.super_rline_id
 * rep_id ... wconf_rref -> rcommit -> rep ---> Nx rcommit.super_rline_id
 * job_id 
 
 wconf_rref - branches/rrefs priorities
 * rref_id

=head1 Relationships, restrictions

 msjobp_cmd  -> msjobp (rcommit_id) -> msjob -> msproc -> msession (machine_id)
   jobp_cmd  ->   jobp (project_id) ->   job
 
 * msjobp.rcommit_id ==> 1x jobp.project_id
 * wconf_job.job_id ==> Nx jobp.project_id
 * rref ==> 1x rcommit ==> 1x rep ==> 1x project
