=head1 ToDo

Not YET here. See http://dev.taptinder.org/wiki/Dev-tt_setup for outdated instructions.

=head1 Fedora 15

=head2 Devel prerequsities

 su
 yum install perl-App-cpanminus
 cpanm Test::NoTabs
 cpanm Test::Pod
 cpanm Test::Pod::Coverage
 cpanm Dist::Zilla
 dzil authordeps | cpanm
 cpanm Archive::Tar::Wrapper