=head1 Present

We are L<building Parrot|"http://tt.taptinder.org/"> (on some platforms, build 
configurations and git branches) and reporting to IRC 
(L<[1]|"http://irclog.perlgeek.de/search.pl?channel=parrot&nick=ttbot&q=">, 
L<[2]|"http://irclog.perlgeek.de/search.pl?channel=parrot&nick=&q=ttbot">). Many 
of processes and configurations are manually maintained.

=head1 Near future

Continuous integration for L<Parrot|"https://github.com/parrot"> and 
L<Perl 6|"http://modules.perl6.org/"> related projects with source code 
on GitHub and L<TAP|"http://en.wikipedia.org/wiki/Test_Anything_Protocol"> 
(Test Anything Protocol) support. Report build failures and test cases 
failures in diff format to email list and IRC on many platforms and 
configurations. Have same really fast machines to nearly real-time 
response after each commit. Be free - use build farms dedicated too 
open source and programmers' machines. Be more public visible and have 
real development team (three or more hackers).

=head1 Future

... a long list in our heads, we should reduce our
L<issue list|"https://github.com/mj41/TapTinder/issues"> before planning 
too much.

See also our 
L<TapTinder's milestones|"https://github.com/mj41/TapTinder/issues/milestones">.
